### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by poupotte**
* Make option port mandatory for `deploy`
* Improve `update-image` function (use vagrant box update)
* Add comments
* Improve function descriptions
* Change vm:stop (use vagrant --force halt)
* Display url in deploy function only for user application

### CODE REVIEW

**Comment by jsilvestre** [comment]
@poupotte the PR can't be merged automatically, can you have a look at it?

Thanks!

**Comment by poupotte** [comment]
@jsilvestre , @aenario   it's ok for you ?

**Comment by jsilvestre** [comment]
Looks good to me !

**Comment by aenario** [comment]
me too

**Comment by aenario** [comment]
published as #v1.0.21

**Comment by frankrousseau** [comment]
Yesterday I dirty-fixed the check version command. It failed on the first startup of development virtual machine.

**Pull request merged**
