### PR TITLE
Remove `util.print`

### PR DESCRIPTION
**Pull request by m4dz**
This commit replace `util.print` command (which is deprecated in
node >= 0.12) in favor of `printit`.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Why don't you use a single instance of printit?

**Comment by jsilvestre** [comment]
There was a reason for using util.print and not printit here, but the developer was lazy and didn't write a comment to explain what it was. I suggest we beat this developer until he can bearly breath, but that we make sure it always work with every single command and case of cozy-dev first.

**Comment by m4dz** [comment]
Because of the prefix :smile:. If we use the same one (`(spawn)    ` with 4 spaces), then we've got output messages like:
```
info - (spawn)    | message
info - (spawn)    | message
error - (spawn)    | error
```

and we loose the padding alignment. So i use a prefix with only 3 spaces in the error case. But I agree this is only cosmetic and it's probably more the responsibility of printit to format messages padding for its own stack (using tabs?) rather to manually deal with it :wink:.

**Comment by frankrousseau** [comment]
Ok. don't worry about that. Padding is too hard to handle for printit. When there is no padding, error are not aligned. When there is a padding and no error, info has an extra space.

**Pull request merged**
